#! /usr/bin/awk -f

BEGIN {
    FS="~"
    total_sum=0
}


/[0-9][0-9]\/[0-9][0-9]\/2[0-9][0-9][0-9]/{
    shop = substr($2, 0, 40);
    gsub(/Varekjøp /, "", shop)
    gsub(/Giro  /, "", shop)
    gsub(/Visa  /, "", shop)
    gsub(/i butikk /, "", shop)

    sum = $4;
    gsub(/,/, "", sum);
    shops[shop] += sum;
    total_sum += sum;
    shop_visits[shop]++;
}
END {
    for (shop in shops) {
        if (shops[shop] == 0) {
            continue;
        }
        print shop, "# Total spent:", shops[shop], "# Visits:", shop_visits[shop];
    }
    print "Total sum:", total_sum
}
